name: Trigger Netlify Build

on:
  push:
    branches: [ "main" ]

concurrency:
  group: netlify-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          echo "Calling Netlify build hook…"
          curl -sSf -X POST -H "Content-Type: application/json" -d '{}' "$NETLIFY_BUILD_HOOK_URL"
          echo "Hook called successfully."
